version: '3'

services:

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80" # porta do host:porta do container

networks:
  laranet:
    driver: bridge

# Para buildar novamente:
# docker-compose up --build